name: learn-github-actions
on: [push]
jobs:
  Hola:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
  Mostrar_etc:
    runs-on: ubuntu-latest
    steps:
      - run: ls /etc
      
  mostrar_ocultos:
   runs-on: ubuntu-latest
   steps:
     - run: |    
        ls -a /
     
  mostrar_ocultos2:
   runs-on: ubuntu-latest
   steps:
     - run: |    
        ls -a /
        
  mostrar_ubicacion:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
