name: Hola

on: [push]

jobs:
  check-beats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: echo a string
      - run: npm install -g bats
      - run: bats -v
 
